shaders:
    clock_analog:
        fragment: ~/.glslScreenSaver/shaders/clock_analog.frag

    defrag:
        fragment: ~/.glslScreenSaver/shaders/defrag.frag

    grayscot:
        fragment: ~/.glslScreenSaver/shaders/grayscot.frag

    ikeda:
        fragment: ~/.glslScreenSaver/shaders/ikeda.frag

    values:
        fragment: ~/.glslScreenSaver/shaders/values.frag

wait: 300 # in seconds
screensaver: [clock_analog, defrag, grayscot, ikeda, value ]
# screensaver: values
